### ISSUE TITLE
resolving all instances of an unregistered token throws an exception

### ISSUE THREAD

**Issue by ArjixWasTaken** [exuanbo/di-wise#16]
## repro:

[JSFiddle](https://jsfiddle.net/ArjixWasTaken/q05ta1d2/20/)
```typescript
import { createContainer, Type } from "di-wise";

class MyClass {}

const container = createContainer();
const token = Type<MyClass>("MyClass");

const instances = container.resolveAll(token);
```

## expectation
```typescript
instances.length === 0
```

## reality
An error is thrown saying that the token `Type<MyClass>` is not registered.

## suggestion
Just for the `resolveAll` method, allow resolving unknown tokens, by simply returning an empty list.

**Comment by exuanbo** [comment]
Hi, optional injection for `resolveAll` can be achieved by adding `Type.Null` or `Type.Undefined` in the arguments: `null` and `undefined` will be filtered out, resulting in an empty array.

```ts
import { createContainer, Type } from "di-wise";

class MyClass {}

const container = createContainer();
const token = Type<MyClass>("MyClass");

const instances = container.resolveAll(token, Type.Null);
//    ^?const instances: MyClass[]
```

My intension is to align the behavior of `resolve` and `resolveAll`: unregistered token will error, adding additional tokens to provide fallback.

**Comment by ArjixWasTaken** [comment]
That does make sense, and I understand the reason you've implemented it that way.
Sadly, that means I'll have to communicate with others to always have a fallback when using `resolveAll`.

I guess I can simply make a wrapper around the method to provide the fallback that way.

**Comment by exuanbo** [comment]
I think a middle simply like this would help,

```ts
import {type Middleware, type Token, Type} from "di-wise";

export const resolveAllOptional: Middleware = (composer) => {
  composer.use("resolveAll", (next) => <Value>(...args: Token<Value>[]) => {
    return next(...args, Type.Null);
  });
};

// use middleware
const container = applyMiddleware(createContainer(), [resolveAllOptional]);
```

I will add this middleware in the next minor version.

**Comment by ArjixWasTaken** [comment]
oooooooh!
that would be amazing!

**Comment by exuanbo** [comment]
Hi, `v0.2.7` is published with middleware [`resolveAllSafe`](https://exuanbo.xyz/di-wise/functions/middlewares.resolveAllSafe.html)

```ts
import {resolveAllSafe} from "di-wise/middlewares";
```

https://github.com/exuanbo/di-wise/blob/f4c08ff77a39001657d54dd68a4f5bacdf9f9f76/src/middlewares/resolve-all-safe.ts#L18-L22
